/*
  Do not edit this file, it is automatically generated from:
  <D:/proj/github/lukezhang-123/database-mysql/mysql-5.7-msvc-gui-proj/scripts/mysql_system_tables_data.sql>
*/
const char* mysql_system_data[]={
NULL
};
